name: Push to main
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      - name: Install dependencies
        run: npm install

      - name: Predeploy
        run: npm run predeploy

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
